# 관리자 권한
sudo: required

# 언어 선택
language: generic

# 도커 환경 구성
services:
    - docker

# 스크립트 실행 환경
before_install:
    - docker build -t younghwani/docker-react-test -f Dockerfile.dev .

# 실행할 스크립트
script:
    - docker run -e CI=true younghwani/docker-react-test npm run test -- --coverage

# 테스트 성공 후
after_success:
    - echo "Test Success"
