sudo: required
services:
    - docker

before_install:
    - docker build -t younghwani/docker-react-test -f Dockerfile.dev .

script:
    - docker run younghwani/docker-react-test npm run test -- --coverage
